In [1]:
import numpy as np

# Creating Arrays

In [ ]:
# One Dimenntion

In [4]:
n = np.array([1,2,4])
n

array([1, 2, 4])

In [5]:
# Two Dimention 

In [10]:
two_d = np.array([(1,2,3),(4,5,6)])
two_d

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
multiple_d = np.array([(1,2,3),(4,5,6),(7,8,9)], dtype = float)
multiple_d

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [17]:
# syntax :- numpy.zeros(shape, dtype = None, order = 'C')
# 
# shape : integer or sequence of integers
# order  : C_contiguous or F_contiguous
#          C-contiguous order in memory(last index varies the fastest)
#          C order means that operating row-rise on the array will be slightly quicker
#          FORTRAN-contiguous order in memory (first index varies the fastest).
#          F order means that column-wise operations will be faster. 
# dtype : [optional, float(byDeafult)] Data type of returned array. 


'\nshape : integer or sequence of integers\norder  : C_contiguous or F_contiguous\n         C-contiguous order in memory(last index varies the fastest)\n         C order means that operating row-rise on the array will be slightly quicker\n         FORTRAN-contiguous order in memory (first index varies the fastest).\n         F order means that column-wise operations will be faster. \ndtype : [optional, float(byDeafult)] Data type of returned array. \n\n'

In [21]:
np.zeros((10,1),int,'f')

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]])

In [22]:
# Syntax: numpy.ones(shape, dtype = None, order = 'C') 
# 
# shape : integer or sequence of integers
# order  : C_contiguous or F_contiguous
#          C-contiguous order in memory(last index varies the fastest)
#          C order means that operating row-rise on the array will be slightly quicker
#          FORTRAN-contiguous order in memory (first index varies the fastest).
#          F order means that column-wise operations will be faster. 
# dtype : [optional, float(byDeafult)] Data type of returned array. 


In [23]:
np.ones((10,10),int,'c')

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [24]:
# The arange([start,] stop[, step,][, dtype]) 
# arange Returns an array with evenly spaced elements as per the interval.
# The interval mentioned is half-opened i.e. [Start, Stop) 
# start : [optional] start of interval range. By default start = 0
# stop  : end of interval range
# step  : [optional] step size of interval. By default step size = 1,  
# For any output out, this is the distance between two adjacent values, out[i+1] - out[i]. 
# dtype : type of output array

In [29]:
np.arange(0,101,10, dtype=float)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [27]:
np.arange(0,21,2, dtype = int)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [47]:
# The numpy.linspace() function returns number spaces evenly w.r.t interval. 
# Similar to numpy.arange() function but instead of step it uses sample number. 


# numpy.linspace(start,
#                stop,
#                num = 50,
#                endpoint = True,
#                retstep = False,
#                dtype = None)
# -> start  : [optional] start of interval range. By default start = 0
# -> stop   : end of interval range
# -> retstep : If True, return (samples, step). 
#  By default restep = False( True means sample will be [start,stop], False means [start,stop)])
# -> num    : [int, optional] No. of samples to generate
# -> dtype  : type of output array

In [38]:
np.linspace(start = -30, stop=1000, num = 5, retstep = True)

(array([ -30. ,  227.5,  485. ,  742.5, 1000. ]), 257.5)

In [46]:
np.linspace(1,10,20,False)

array([1.  , 1.45, 1.9 , 2.35, 2.8 , 3.25, 3.7 , 4.15, 4.6 , 5.05, 5.5 ,
       5.95, 6.4 , 6.85, 7.3 , 7.75, 8.2 , 8.65, 9.1 , 9.55])

In [ ]:
# numpy.full(shape, fill_value, dtype = None, order = ‘C’) :
# Return a new array with the same shape and type as a given array filled with a fill_value.shape : Number of rows
# order      : C_contiguous or F_contiguous
# dtype      : [optional, float(by Default)] Data type of returned array.  
# fill_value : [bool, optional] Value to fill in the array.

In [48]:
np.full([1,10],99,dtype = int, order = 'c')

array([[99, 99, 99, 99, 99, 99, 99, 99, 99, 99]])

In [49]:
np.full([10,10],9,dtype = int, order = 'f')

array([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [ ]:
# numpy.eye(R, C = None, k = 0, dtype = type <‘float’>) 
# : –The eye tool returns a 2-D array with  1’s as the diagonal and  0’s elsewhere. 
# The diagonal can be main, upper, or lower depending on the optional parameter k. 
# A positive k is for the upper diagonal,
# a negative k is for the lower, and a  0 k (default) is for the main diagonal.

In [ ]:
# R : Number of rows
# C : [optional] Number of columns; By default M = N
# k : [int, optional, 0 by default]
#           Diagonal we require; k>0 means diagonal above main diagonal or vice versa.
# dtype : [optional, float(by Default)] Data type of returned array.  

In [50]:
np.eye(3,dtype = int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [51]:
np.eye(3,k = 1,dtype = int)

array([[0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]])

In [54]:
np.eye(3,k = 2,dtype = int)

array([[0, 0, 1],
       [0, 0, 0],
       [0, 0, 0]])

In [55]:
np.eye(3,k = 3,dtype = int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [56]:
np.eye(3,k = -1,dtype = int)

array([[0, 0, 0],
       [1, 0, 0],
       [0, 1, 0]])

In [57]:
np.eye(3,k = -2,dtype = int)

array([[0, 0, 0],
       [0, 0, 0],
       [1, 0, 0]])

In [58]:
np.eye(3,k = -3,dtype = int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [63]:
np.eye(3, 2,0,dtype = int)

array([[1, 0],
       [0, 1],
       [0, 0]])

In [65]:
# numpy.random.random() is one of the function for doing random sampling in numpy. 
# It returns an array of specified shape and fills it with random floats in the half-open interval [0.0, 1.0).
# Syntax : numpy.random.random(size=None)

# Parameters :
# size : [int or tuple of ints, optional] Output shape. If the given shape is, e.g., (m, n, k), then m * n * k samples are drawn. Default is None, in which case a single value is returned.

# Return : Array of random floats in the interval [0.0, 1.0). or a single such random float if size not provided.

In [68]:
np.random.random((3,4)) 

array([[0.57157659, 0.00333789, 0.3938436 , 0.28676072],
       [0.26110535, 0.91083745, 0.64739973, 0.01666291],
       [0.33264404, 0.6243731 , 0.17473249, 0.98790407]])

In [69]:
# numpy.empty(shape, dtype = float, order = ‘C’) :
# Return a new array of given shape and type, with random values.
# Parameters :

# -> shape : Number of rows
# -> order : C_contiguous or F_contiguous
# -> dtype : [optional, float(by Default)] Data type of returned array.

In [76]:
np.empty((1,10) , order = 'c')

array([[ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.]])

In [77]:
# Saving & Loading On Disk

In [ ]:
# numpy.save()function is used to store the input array in a disk file with npy extension(.npy).

# Syntax : numpy.save(file, arr, allow_pickle=True, fix_imports=True)

# Parameters:
# file : : File or filename to which the data is saved. If file is a string or Path, a .npy extension will be appended to the file name if it does not already have one.If file is a file-object, then the filename is unchanged.
# allow_pickle : : Allow saving object arrays using Python pickles. Reasons for disallowing pickles include security (loading pickled data can execute arbitrary code) and portability (pickled objects may not be loadable on different Python installations). Default: True
# fix_imports : Only useful in forcing objects in object arrays on Python 3 to be pickled in a Python 2 compatible way.
# arr : Array data to be saved.

# Return : Stores the input array in a disk file with npy extension(.npy).

In [85]:
a = np.empty((7,6),int)

In [86]:
np.save("test",a)

In [88]:
np.load('test.npy')

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [89]:
b = np.sin(a)

In [120]:
np.savez('sine',a,b)

In [121]:
result_files = np.load('sine.npz')

In [122]:
result_files.files

['arr_0', 'arr_1']

In [123]:
result_files['arr_0']


array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [124]:
result_files['arr_1']

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [125]:
c = np.ones((12,10), int)
c

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [116]:
# we can store multiple np.arrays
np.savez("hello",a,b,c)

In [126]:
np.load('hello.npz')['arr_1']

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

# Saving and Loading from text files 
##  np.loadtxt( )

##  np.genfromtxt( , delimiter= )

##  np.savetxt( , a, delimiter= )

In [ ]:
# numpy.load() in Python is used load data from a text file, with aim to be a fast reader for simple text files.

# Note that each row in the text file must have the same number of values.

# Syntax: numpy.loadtxt(fname, dtype=’float’, comments=’#’, delimiter=None, converters=None, skiprows=0, usecols=None, unpack=False, ndmin=0)

# Parameters:
# fname : File, filename, or generator to read. If the filename extension is .gz or .bz2, the file is first decompressed. Note that generators should return byte strings for Python 3k.
# dtype : Data-type of the resulting array; default: float. If this is a structured data-type, the resulting array will be 1-dimensional, and each row will be interpreted as an element of the array.
# delimiter : The string used to separate values. By default, this is any whitespace.
# converters : A dictionary mapping column number to a function that will convert that column to a float. E.g., if column 0 is a date string: converters = {0: datestr2num}. Default: None.
# skiprows : Skip the first skiprows lines; default: 0.

In [128]:
# Python program explaining
# loadtxt() function
import numpy as geek

# StringIO behaves like a file object
from io import StringIO

c = StringIO("0 1 2 \n3 4 5")
d = geek.loadtxt(c)

print(d)


[[0. 1. 2.]
 [3. 4. 5.]]


In [143]:
# Python program explaining
# loadtxt() function
import numpy as geek

# StringIO behaves like a file object
from io import StringIO

c = StringIO("1, 2, 3\n4, 5, 6\n7, 8, 9\n")
x, y , z  = geek.loadtxt(c, delimiter =', ', usecols =(0, 1, 2),unpack = True)

print("x is: ", x)
print("y is: ", y)
print("z is: ", z)


x is:  [1. 4. 7.]
y is:  [2. 5. 8.]
z is:  [3. 6. 9.]
